DROP TABLE MENUTIPOCOMIDA;
DROP TABLE MENU;
DROP TABLE REPRESENTANTE;
DROP TABLE RESTAURANTE;
DROP TABLE PRODUCTOINGREDIENTE;
DROP TABLE INGREDIENTE;
DROP TABLE TIPOCOMIDA;
DROP TABLE PRODUCTO;
DROP TABLE CATEGORIA;
DROP TABLE REGISTRO;

CREATE TABLE REGISTRO(
   CODIGO INTEGER NOT NULL,
   USUARIO VARCHAR(100) NOT NULL,
   CONTRASENIA VARCHAR(100) NOT NULL,
   PERMISOS INTEGER NOT NULL,
   CONSTRAINT PK_REGISTRO PRIMARY KEY (CODIGO)
);

CREATE TABLE CATEGORIA(
  ID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  NOMBRE VARCHAR2(100 BYTE) NOT NULL,
  CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID)
);

CREATE TABLE PRODUCTO(
  ID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  NOMBRE VARCHAR2(100 BYTE) NOT NULL,
  DESCRIPCION VARCHAR2(1000 BYTE)  NOT NULL,
  TRADUCCION VARCHAR2(1100 BYTE) NOT NULL,
  TIEMPOPREPARACION INTEGER NOT NULL,
  CATEGORIA_ID INTEGER NOT NULL,
  CHECK (CATEGORIA_ID>0 AND CATEGORIA_ID<6),
  CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID),
  CONSTRAINT FK_CATEGORIA FOREIGN KEY(CATEGORIA_ID) REFERENCES CATEGORIA(ID)
);

CREATE TABLE TIPOCOMIDA(
   ID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   NOMBRE VARCHAR2(100 BYTE)NOT NULL,
   CONSTRAINT PK_TIPOCOMIDA PRIMARY KEY (ID)
);

CREATE TABLE INGREDIENTE(
  ID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  NOMBRE VARCHAR2(100 BYTE) NOT NULL,
  DESCRIPCION VARCHAR2(1000 BYTE) NOT NULL,
  TRADUCCION VARCHAR2(1100 BYTE) NOT NULL,
  CONSTRAINT PK_INGREDIENTE PRIMARY KEY (ID)
);

CREATE TABLE PRODUCTOINGREDIENTE(
   PRODUCTO_ID INTEGER NOT NULL,
   INGREDIENTE_ID INTEGER NOT NULL,
   CONSTRAINT FK_INGREDIENTE FOREIGN KEY (INGREDIENTE_ID) REFERENCES INGREDIENTE(ID),
   CONSTRAINT FK_PRODUCTO FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTO(ID),
   CONSTRAINT PK_PRODUCTOINGREDIENTE PRIMARY KEY (PRODUCTO_ID,INGREDIENTE_ID)
);


CREATE TABLE RESTAURANTE(
  ID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  NOMBRE VARCHAR2(150 BYTE)NOT NULL,
  PAGINAWEB VARCHAR2(3999 BYTE),
  TIPOCOMIDA_ID NOT NULL, 
  REGISTRO_ID NOT NULL,
  CONSTRAINT FK_REGISTROID FOREIGN KEY (REGISTRO_ID) REFERENCES REGISTRO(CODIGO),
  CONSTRAINT FK_TICOMIDARESTAURANTE FOREIGN KEY (TIPOCOMIDA_ID) REFERENCES TIPOCOMIDA(ID),
  CONSTRAINT PK_RESTAURANTE PRIMARY KEY (ID)
);

CREATE TABLE REPRESENTANTE(
  ID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  NOMBRE VARCHAR2(500 BYTE) NOT NULL,
  TELEFONO INTEGER,
  CORREO VARCHAR2(100 BYTE),
  RESTAURANTE_ID INTEGER NOT NULL UNIQUE,
  CHECK (NOT(TELEFONO IS NULL AND CORREO IS NULL)),
  CONSTRAINT FK_RESTAURANTEREPRESENTANTE FOREIGN KEY (RESTAURANTE_ID) REFERENCES RESTAURANTE(ID),
  CONSTRAINT PK_REPRESENTANTE PRIMARY KEY (ID)
);

CREATE TABLE MENU(
   ID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   CANTIDAD INTEGER NOT NULL,
   COSTODEPRODUCION NUMBER NOT NULL,
   VALORALPUBLICO NUMBER NOT NULL,
   PRODUCTOENTRADA_ID INTEGER,
   PRODUCTOPLATOFUERTE_ID INTEGER,
   PRODUCTOBEBIDA_ID INTEGER,
   PRODUCTOPOSTRE_ID INTEGER,
   PRODUCTOACOMPANAMIENTO_ID INTEGER,
   RESTAURANTE_ID INTEGER NOT NULL,
   CHECK (COSTODEPRODUCION>0 AND VALORALPUBLICO>=0),
   CONSTRAINT FK_PRODUCTOENTRADA FOREIGN KEY (PRODUCTOENTRADA_ID) REFERENCES PRODUCTO(ID),
   CONSTRAINT FK_PRODUCTOPLATOFUERTE FOREIGN KEY (PRODUCTOPLATOFUERTE_ID) REFERENCES PRODUCTO(ID),
   CONSTRAINT FK_PRODUCTOPOSTRE FOREIGN KEY (PRODUCTOPOSTRE_ID) REFERENCES PRODUCTO(ID),
   CONSTRAINT FK_PRODUCTOBEBIDA FOREIGN KEY (PRODUCTOBEBIDA_ID) REFERENCES PRODUCTO(ID),
   CONSTRAINT FK_PRODUCTOACOMPANAMIENTO FOREIGN KEY (PRODUCTOACOMPANAMIENTO_ID) REFERENCES PRODUCTO(ID),
   CONSTRAINT FK_RESTAURANTE FOREIGN KEY (RESTAURANTE_ID) REFERENCES RESTAURANTE(ID),
   CONSTRAINT PK_MENU PRIMARY KEY (ID)
);

CREATE TABLE MENUTIPOCOMIDA(
   MENU_ID INTEGER NOT NULL,
   TIPOCOMIDA_ID INTEGER NOT NULL,
   CONSTRAINT FK_MENUMENUTIPOCOMIDA FOREIGN KEY (MENU_ID) REFERENCES MENU(ID),
   CONSTRAINT FK_TIPOCOMIDAMENUTIPOCOMIDA FOREIGN KEY (TIPOCOMIDA_ID) REFERENCES TIPOCOMIDA(ID),
   CONSTRAINT PK_MENUTIPOCOMIDA PRIMARY KEY (MENU_ID,TIPOCOMIDA_ID)
);

INSERT INTO REGISTRO ( CODIGO,USUARIO,CONTRASENIA,PERMISOS) VALUES (12345,'ADIMIN','12345',3);
INSERT INTO REGISTRO ( CODIGO,USUARIO,CONTRASENIA,PERMISOS) VALUES (0,'RESTAURANTEROCHA','12345',2);
INSERT INTO REGISTRO ( CODIGO,USUARIO,CONTRASENIA,PERMISOS) VALUES (54321,'PIZERRIAALPES','12345',2); 

INSERT INTO CATEGORIA(NOMBRE) VALUES ('ENTRADA');
INSERT INTO CATEGORIA(NOMBRE) VALUES ('PLATOFUERTE');
INSERT INTO CATEGORIA(NOMBRE) VALUES ('POSTRE');
INSERT INTO CATEGORIA(NOMBRE) VALUES ('BEBIDA');
INSERT INTO CATEGORIA(NOMBRE) VALUES ('ACOMPANAMIENTO');

INSERT INTO PRODUCTO (NOMBRE,DESCRIPCION,TRADUCCION,TIEMPOPREPARACION,CATEGORIA_ID) VALUES ('pizza','Comida que consiste en una base de masa de pan, generalmente delgada y redonda, que se recubre con salsa de tomate, queso mozzarella o similar y diversos ingredientes troceados y se cuece al horno; es de origen italiano.','Food consisting of a base of bread dough, usually thin and round, covered with tomato sauce, mozzarella or similar cheese and various ingredients chopped and baked; is of Italian origin.',15,2);
INSERT INTO PRODUCTO (NOMBRE,DESCRIPCION,TRADUCCION,TIEMPOPREPARACION,CATEGORIA_ID)  VALUES ('hamburgesa','Comida que se prepara con carne picada de animales vacunos, cerdo o aves, generalmente condimentada con sal, pimienta, ajo y perejil, y forma redonda y plana; suele asarse a la plancha o freírse.','Food prepared with minced beef, pork or poultry, usually seasoned with salt, pepper, garlic and parsley, and round and flat shape; usually grilled or fried.',20,2);
INSERT INTO PRODUCTO (NOMBRE,DESCRIPCION,TRADUCCION,TIEMPOPREPARACION,CATEGORIA_ID) VALUES ('ajiaco santafereño',' el ajiaco santafereño es una platillo típico de la ciudad de Bogotá, Colombia. Su nombre lo toma de Santa Fé, como en tiempos coloniales se le conoció a esta capital suramericana.Con el pollo y tres clases de papa como su componente esencial, el ajiaco santafereño es una receta que usted debería probar','the ajiaco santafereño is a typical dish of the city of Bogotá, Colombia. Its name takes it from Santa Fe, as in colonial times it was known to this South American capital.With chicken and three kinds of potato as its essential component, Santa Fe chili is a recipe that you should try.',30,2);
INSERT INTO PRODUCTO (NOMBRE,DESCRIPCION,TRADUCCION,TIEMPOPREPARACION,CATEGORIA_ID) VALUES ('patacones','es una comida a base de trozos aplanados fritos de plátano verde','is a meal based on flat fried pieces of green banana',10,1);
INSERT INTO PRODUCTO (NOMBRE,DESCRIPCION,TRADUCCION,TIEMPOPREPARACION,CATEGORIA_ID) VALUES ('chorizos',' es un producto embutido, curado, elaborado a partir de carnes frescas de cerdo graso','is an in-built, cured product made from fresh fatty pork meats',10,1);
INSERT INTO PRODUCTO (NOMBRE,DESCRIPCION,TRADUCCION,TIEMPOPREPARACION,CATEGORIA_ID) VALUES ('brownie con helado','brownie helado','brownie 6 ice cream',15,3);
INSERT INTO PRODUCTO (NOMBRE,DESCRIPCION,TRADUCCION,TIEMPOPREPARACION,CATEGORIA_ID) VALUES ('chicha','bebidas derivadas principalmente de la fermentación no destilada del maíz y otros cereales originarios de América','beverages derived mainly from the non-distilled fermentation of maize and other cereals originating in the Americas',15,4);
INSERT INTO PRODUCTO (NOMBRE,DESCRIPCION,TRADUCCION,TIEMPOPREPARACION,CATEGORIA_ID) VALUES ('huevo frito','huevo frito','fried egg',15,5);

INSERT INTO Ingrediente (Nombre,Descripcion,Traduccion) Values ('amor','el ingrediente mas importantes (valido para todos los products de rotondantes)','the most important ingredient (valid for all rotondantes products)');
INSERT INTO Ingrediente (Nombre,Descripcion,Traduccion) Values ('queso','Alimento sólido que se obtiene por maduración de la cuajada de la leche una vez eliminado el suero; sus diferentes variedades dependen del origen de la leche empleada, de los métodos de elaboración seguidos y del grado de madurez alcanzado.','Solid food obtained by maturation of the milk curd after the serum is eliminated; its various variants depend on the origin of the milk used, the methods of processing followed and the degree of maturity reached.');
INSERT INTO Ingrediente (Nombre,Descripcion,Traduccion) Values ('papa','tuberculo comestible despues de una coccion determinada','edible tuberculus after a certain cooking.');
INSERT INTO Ingrediente (Nombre,Descripcion,Traduccion) Values ('tomate','Baya casi roja, fruto de la tomatera, de superficie lisa y brillante, en cuya pulpa hay numerosas semillas algo aplastadas y amarillas.','Almost red berry, fruit of the tomatera, with smooth and shiny surface, in whose pulp there are numerous seeds somewhat crushed and yellow.');
INSERT INTO Ingrediente (Nombre,Descripcion,Traduccion) Values ('pollo',' es el nombre que reciben las crías de las gallinas y de otras aves.','is the name given to the offspring of hens and other birds.');

INSERT INTO TIPOCOMIDA (NOMBRE) VALUES ('indu');
INSERT INTO TIPOCOMIDA (NOMBRE) VALUES ('arabe');
INSERT INTO TIPOCOMIDA (NOMBRE) VALUES ('vegetariana');
INSERT INTO TIPOCOMIDA (NOMBRE) VALUES ('marciana');
INSERT INTO TIPOCOMIDA (NOMBRE) VALUES ('rapida');

INSERT INTO RESTAURANTE (NOMBRE,PAGINAWEB,TIPOCOMIDA_ID,REGISTRO_ID ) VALUES ('pizzeria los alpes','https://pizzeriadelosalpes.wixsite.com/pizzeriadelosalpes',5,54321);
INSERT INTO RESTAURANTE (NOMBRE,PAGINAWEB,TIPOCOMIDA_ID,REGISTRO_ID ) VALUES ('la tiendita de rocha','https://que_es_esa_mierda',4,0);

INSERT INTO REPRESENTANTE ( NOMBRE,TELEFONO,CORREO,RESTAURANTE_ID) VALUES ('rocha',123456,'nomeacuedo@uniandes.edu.co',2);

INSERT INTO MENU (CANTIDAD,COSTODEPRODUCION,VALORALPUBLICO,PRODUCTOENTRADA_ID,PRODUCTOPLATOFUERTE_ID,PRODUCTOPOSTRE_ID ,PRODUCTOBEBIDA_ID,PRODUCTOACOMPANAMIENTO_ID,RESTAURANTE_ID) VALUES (30,3000,5000,NULL,1,NULL,NULL,NULL,1);
INSERT INTO MENU (CANTIDAD,COSTODEPRODUCION,VALORALPUBLICO,PRODUCTOENTRADA_ID,PRODUCTOPLATOFUERTE_ID,PRODUCTOPOSTRE_ID ,PRODUCTOBEBIDA_ID,PRODUCTOACOMPANAMIENTO_ID,RESTAURANTE_ID) VALUES (6,5000,20000,5,3,6,7,8,2);

INSERT INTO MENUTIPOCOMIDA (MENU_ID,TIPOCOMIDA_ID) VALUES (1,5);
INSERT INTO MENUTIPOCOMIDA (MENU_ID,TIPOCOMIDA_ID) VALUES (2,4);

INSERT INTO Productoingrediente (Producto_Id,Ingrediente_Id) Values (1,1);
INSERT INTO Productoingrediente (Producto_Id,Ingrediente_Id) Values (1,2);
INSERT INTO Productoingrediente (Producto_Id,Ingrediente_Id) Values (1,3);
INSERT INTO Productoingrediente (Producto_Id,Ingrediente_Id) Values (2,1);
INSERT INTO Productoingrediente (Producto_Id,Ingrediente_Id) Values (3,1);
INSERT INTO Productoingrediente (Producto_Id,Ingrediente_Id) Values (3,5);
INSERT INTO PRODUCTOINGREDIENTE (PRODUCTO_ID,INGREDIENTE_ID) VALUES (3,3);

COMMIT;
